[workspace]
members = [
    "crates/snow_cli",
    "crates/snow_core",
    "crates/snow_daemon",
    "crates/snow_mcp",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["clock", "serde"] }
clap = { version = "4", features = ["derive"] }
colored = "3"
crossterm = "0.29"
dirs = "6.0.0"
dotenvy = "0.15"
interprocess = { version = "2.4.2", features = ["tokio"] }
open = "5"
ratatui = "0.30"
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
servicenow_rs = { git = "https://github.com/trepidity/servicenow_rs.git", rev = "12cf719d1f3d45d73d99979e2cf893afc5da60c4" }
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
tracing = "0.1"
uuid = { version = "1", features = ["serde", "v4"] }
