#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RpcMethod {
    ContractInfo,
    CachePolicyValidate,
    CachePolicyReload,
    GetRecord,
    GetRecordFresh,
    GetKnowledgeArticle,
    GetKnowledgeArticleFresh,
    GetArticle,
    GetArticleFresh,
    TaskSlaStatus,
    TaskSlaStatusForTasks,
    SearchKnowledge,
    KbSemanticSearch,
    SearchRecords,
    UserLookup,
    UserSearch,
    BusinessApplicationGet,
    BusinessApplicationGetFresh,
    BusinessApplicationSearch,
    BusinessApplicationQuery,
    BusinessApplicationServers,
    BusinessApplicationServersCached,
    BusinessApplicationsForServer,
    BusinessApplicationSync,
    BusinessApplicationFields,
    ResourcePlanList,
    IncidentListByAssignmentGroup,
    IncidentGet,
    IncidentQuery,
    IncidentAssignmentGroups,
    IncidentFields,
    IncidentAssignmentGroupQueue,
    ServerGet,
    ServerGetFresh,
    ServerSearch,
    ServerQuery,
    ServerFields,
    ListKnowledgeBases,
    ListCategories,
    ListKnowledgeArticles,
    GetApproval,
    CatalogItemsSearch,
    CatalogItemGet,
    CatalogPlanRequest,
    CatalogSubmitRequest,
    GetChildren,
    ChangeRequestListTasks,
    GetWorkNotes,
    ListRecords,
    RecordQuery,
    ListMyTasks,
    ListMyApprovals,
    ListMyProjects,
    ListMyStories,
    ListMyIncidents,
    MyTasks,
    MyTasksFresh,
    MyApprovals,
    MyApprovalsFresh,
    MyProjects,
    MyProjectsFresh,
    MyStoriesFresh,
    MyIncidentsFresh,
    VaultPath,
    AddWorkNote,
    AttachmentList,
    AttachmentUpload,
    SetState,
    FieldChoices,
    Approve,
    Reject,
    ApprovalApprove,
    ApprovalReject,
    GetDegradedReads,
    CacheInfo,
    RepairVault,
    VerifyVault,
    PruneOrphans,
    RefreshAll,
    KbSync,
    KbListTags,
    KbStatus,
    KbSemanticStatus,
    KbSemanticRebuild,
    SchedulerStatus,
    SchedulerTriggerNow,
    StartJob,
    GetJob,
    ListJobs,
    CancelJob,
    PlanGet,
    WorkNotePlanAdd,
    WorkNoteApplyAdd,
    ChangeRequestPlanCreate,
    ChangeRequestApplyCreate,
    ChangeRequestPlanUpdate,
    ChangeRequestApplyUpdate,
    ChangeTaskPlanCreate,
    ChangeTaskApplyCreate,
    ChangeTaskPlanUpdate,
    ChangeTaskApplyUpdate,
    IncidentPlanUpdate,
    IncidentApplyUpdate,
    IncidentBulkPlanUpdate,
    IncidentBulkApplyUpdate,
    ResourcePlanPlanCreate,
    ResourcePlanApplyCreate,
    ResourcePlanPlanUpdate,
    ResourcePlanApplyUpdate,
    StoryPlanCreate,
    StoryApplyCreate,
    StoryPlanUpdate,
    StoryApplyUpdate,
    StoryTaskPlanCreate,
    StoryTaskApplyCreate,
    StoryTaskPlanUpdate,
    StoryTaskApplyUpdate,
    TimecardList,
    TimecardSetHours,
    TimecardPlanSetHours,
    TimecardApplySetHours,
    Shutdown,
    Ping,
    Unknown,
}

impl RpcMethod {
    pub fn from_method(method: &str) -> Self {
        match method {
            "contract_info" => Self::ContractInfo,
            "cache_policy_validate" => Self::CachePolicyValidate,
            "cache_policy_reload" => Self::CachePolicyReload,
            "get_record" => Self::GetRecord,
            "get_record_fresh" => Self::GetRecordFresh,
            "get_knowledge_article" => Self::GetKnowledgeArticle,
            "get_knowledge_article_fresh" => Self::GetKnowledgeArticleFresh,
            "get_article" => Self::GetArticle,
            "get_article_fresh" => Self::GetArticleFresh,
            "task_sla_status" => Self::TaskSlaStatus,
            "task_sla_status_for_tasks" => Self::TaskSlaStatusForTasks,
            "search_knowledge" => Self::SearchKnowledge,
            "kb_semantic_search" => Self::KbSemanticSearch,
            "search_records" => Self::SearchRecords,
            "user_lookup" => Self::UserLookup,
            "user_search" => Self::UserSearch,
            "business_application_get" => Self::BusinessApplicationGet,
            "business_application_get_fresh" => Self::BusinessApplicationGetFresh,
            "business_application_search" => Self::BusinessApplicationSearch,
            "business_application_query" => Self::BusinessApplicationQuery,
            "business_application_servers" => Self::BusinessApplicationServers,
            "business_application_servers_cached" => Self::BusinessApplicationServersCached,
            "business_applications_for_server" => Self::BusinessApplicationsForServer,
            "business_application_sync" => Self::BusinessApplicationSync,
            "business_application_fields" => Self::BusinessApplicationFields,
            "resource_plan_list" => Self::ResourcePlanList,
            "incident_list_by_assignment_group" => Self::IncidentListByAssignmentGroup,
            "incident_get" => Self::IncidentGet,
            "incident_query" => Self::IncidentQuery,
            "incident_assignment_groups" => Self::IncidentAssignmentGroups,
            "incident_fields" => Self::IncidentFields,
            "incident_assignment_group_queue" => Self::IncidentAssignmentGroupQueue,
            "server_get" => Self::ServerGet,
            "server_get_fresh" => Self::ServerGetFresh,
            "server_search" => Self::ServerSearch,
            "server_query" => Self::ServerQuery,
            "server_fields" => Self::ServerFields,
            "list_knowledge_bases" => Self::ListKnowledgeBases,
            "list_categories" => Self::ListCategories,
            "list_knowledge_articles" => Self::ListKnowledgeArticles,
            "get_approval" => Self::GetApproval,
            "catalog_items_search" => Self::CatalogItemsSearch,
            "catalog_item_get" => Self::CatalogItemGet,
            "catalog_plan_request" => Self::CatalogPlanRequest,
            "catalog_submit_request" => Self::CatalogSubmitRequest,
            "get_children" => Self::GetChildren,
            "change_request_list_tasks" => Self::ChangeRequestListTasks,
            "get_work_notes" => Self::GetWorkNotes,
            "list_records" => Self::ListRecords,
            "record_query" => Self::RecordQuery,
            "list_my_tasks" => Self::ListMyTasks,
            "list_my_approvals" => Self::ListMyApprovals,
            "list_my_projects" => Self::ListMyProjects,
            "list_my_stories" => Self::ListMyStories,
            "list_my_incidents" => Self::ListMyIncidents,
            "my_tasks" => Self::MyTasks,
            "my_tasks_fresh" => Self::MyTasksFresh,
            "my_approvals" => Self::MyApprovals,
            "my_approvals_fresh" => Self::MyApprovalsFresh,
            "my_projects" => Self::MyProjects,
            "my_projects_fresh" => Self::MyProjectsFresh,
            "my_stories_fresh" => Self::MyStoriesFresh,
            "my_incidents_fresh" => Self::MyIncidentsFresh,
            "vault_path" => Self::VaultPath,
            "add_work_note" => Self::AddWorkNote,
            "attachment_list" => Self::AttachmentList,
            "attachment_upload" => Self::AttachmentUpload,
            "set_state" => Self::SetState,
            "field_choices" => Self::FieldChoices,
            "approve" => Self::Approve,
            "reject" => Self::Reject,
            "approval_approve" => Self::ApprovalApprove,
            "approval_reject" => Self::ApprovalReject,
            "get_degraded_reads" => Self::GetDegradedReads,
            "cache_info" => Self::CacheInfo,
            "repair_vault" => Self::RepairVault,
            "verify_vault" => Self::VerifyVault,
            "prune_orphans" => Self::PruneOrphans,
            "refresh_all" => Self::RefreshAll,
            "kb_sync" => Self::KbSync,
            "kb_list_tags" => Self::KbListTags,
            "kb_status" => Self::KbStatus,
            "kb_semantic_status" => Self::KbSemanticStatus,
            "kb_semantic_rebuild" => Self::KbSemanticRebuild,
            "scheduler.status" => Self::SchedulerStatus,
            "scheduler.trigger_now" => Self::SchedulerTriggerNow,
            "start_job" => Self::StartJob,
            "get_job" => Self::GetJob,
            "list_jobs" => Self::ListJobs,
            "cancel_job" => Self::CancelJob,
            "plan_get" => Self::PlanGet,
            "work_note_plan_add" => Self::WorkNotePlanAdd,
            "work_note_apply_add" => Self::WorkNoteApplyAdd,
            "change_request_plan_create" => Self::ChangeRequestPlanCreate,
            "change_request_apply_create" => Self::ChangeRequestApplyCreate,
            "change_request_plan_update" => Self::ChangeRequestPlanUpdate,
            "change_request_apply_update" => Self::ChangeRequestApplyUpdate,
            "change_task_plan_create" => Self::ChangeTaskPlanCreate,
            "change_task_apply_create" => Self::ChangeTaskApplyCreate,
            "change_task_plan_update" => Self::ChangeTaskPlanUpdate,
            "change_task_apply_update" => Self::ChangeTaskApplyUpdate,
            "incident_plan_update" => Self::IncidentPlanUpdate,
            "incident_apply_update" => Self::IncidentApplyUpdate,
            "incident_bulk_plan_update" => Self::IncidentBulkPlanUpdate,
            "incident_bulk_apply_update" => Self::IncidentBulkApplyUpdate,
            "resource_plan_plan_create" => Self::ResourcePlanPlanCreate,
            "resource_plan_apply_create" => Self::ResourcePlanApplyCreate,
            "resource_plan_plan_update" => Self::ResourcePlanPlanUpdate,
            "resource_plan_apply_update" => Self::ResourcePlanApplyUpdate,
            "story_plan_create" => Self::StoryPlanCreate,
            "story_apply_create" => Self::StoryApplyCreate,
            "story_plan_update" => Self::StoryPlanUpdate,
            "story_apply_update" => Self::StoryApplyUpdate,
            "story_task_plan_create" => Self::StoryTaskPlanCreate,
            "story_task_apply_create" => Self::StoryTaskApplyCreate,
            "story_task_plan_update" => Self::StoryTaskPlanUpdate,
            "story_task_apply_update" => Self::StoryTaskApplyUpdate,
            "timecard_list" => Self::TimecardList,
            "timecard_set_hours" => Self::TimecardSetHours,
            "timecard_plan_set_hours" => Self::TimecardPlanSetHours,
            "timecard_apply_set_hours" => Self::TimecardApplySetHours,
            "shutdown" => Self::Shutdown,
            "ping" => Self::Ping,
            _ => Self::Unknown,
        }
    }
}
